function T=TransMatrix(alpha_rad)

T=[cos(alpha_rad)^2,sin(alpha_rad)^2,sin(2*alpha_rad); ...
   sin(alpha_rad)^2,cos(alpha_rad)^2,-sin(2*alpha_rad); ...
   -sin(2*alpha_rad)/2,sin(2*alpha_rad)/2,cos(2*alpha_rad)];